language: node_js
node_js:
  - "node"
  - "stable"
env:
  global:
    - CC_TEST_REPORTER_ID=84934c5c0aef9e3da392258cef499f51c595a79f0d35ca8e6baf6a02ece4a450
before_install:
  - npm i -g npm@5.6.0
cache:
  directories:
    - "node_modules"
dist: trusty
sudo: required
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test  
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT




